GLEW_INCLUDE = /usr/local/include
GLEW_LIB = /usr/local/lib

all: hello-gl hello-gl-dummy

hello-gl: hello-gl.o util.o
	gcc -o hello-gl $^ -framework GLUT -framework OpenGL -L$(GLEW_LIB) -lGLEW

hello-gl-dummy: hello-gl-dummy.o
	gcc -o hello-gl-dummy $^ -framework GLUT -framework OpenGL -L$(GLEW_LIB) -lGLEW

.c.o:
	gcc -c -o $@ $< -I$(GLEW_INCLUDE)

clean:
	rm -f hello-gl hello-gl-dummy hello-gl.o util.o hello-gl-dummy.o

